name: app
description: dbcwallet built with Flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.i.eventId == 'Reward';
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+3001

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.0
  flutter_svg: ^0.23.0+1
  json_annotation: ^4.0.1
  #  json_annotation: ^3.1.1
  get_storage: ^2.0.2
  biometric_storage: ^2.0.2
  update_app: ^0.1.7
  # device_info: ^2.0.1
  package_info: ^2.0.2
  uni_links: ^0.5.1
  # firebase_core: 1.5.0
  # firebase_analytics: 8.3.0
  flutter_screenutil: ^5.0.0+2
  #  firebase_messaging: 10.0.5
  fl_chart: ^0.45.0

  # jpush_flutter:
  #   git:
  #     url: https://github.com/polkawallet-io/jpush-flutter-plugin.git
  #     ref: a2ee9893ec9115a15bb25d4a59c7cbaa447e14b6
  # polkawallet_plugin_kusama:
  #   git:
  #     url: https://github.com/polkawallet-io/polkawallet_plugin_kusama.git
  #     ref: 8a6528d6c174cde5f9408c2212572e9288f5eec9
  # polkawallet_plugin_acala:
  #   git:
  #     url: https://github.com/AcalaNetwork/polkawallet_plugin_acala.git
  #     ref: 4e9f4f714666a5e6214fff9e5a89df03d62b756b
  # polkawallet_plugin_karura:
  #   git:
  #     url: https://github.com/AcalaNetwork/polkawallet_plugin_karura.git
  #     ref: 5db24a99a47728bac59400f10ce0a426ffd71174
  # polkawallet_plugin_statemine:
  #   git:
  #     url: https://github.com/polkawallet-io/polkawallet_plugin_statemine.git
  #     ref: 7d8cf727c5eb78d97205e53fe2ade55c513754a9
  # polkawallet_plugin_laminar:
  #   git:
  #     url: https://github.com/polkawallet-io/polkawallet_plugin_laminar.git
  #     ref: 7950c74abe74494aed49662b37dcebdacf1013c1
  # polkawallet_plugin_bifrost:
  #   git:
  #     url: https://github.com/bifrost-finance/polkawallet_plugin_bifrost.git
  #     ref: 87c54fe160c88992d04c8ce30ef23fe09e9732af
  # polkawallet_plugin_chainx:
  #   git:
  #     url: https://github.com/chainx-org/polkawallet_plugin_chainx.git
  #     ref: 2cc634bc4f0b873e7fe0801d5d3fba46756f5315
  # polkawallet_plugin_edgeware:
  #   git:
  #     url: https://github.com/remzrn/polkawallet_plugin_edgeware.git
  #     ref: 11be316dc77b721d41ed6774fbf8d444a5a8eaa9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  polkawallet_sdk:
    git:
      url: https://github.com/polkawallet-io/sdk.git
      ref: "0.4.1"
  polkawallet_ui:
    git:
      url: https://github.com/polkawallet-io/ui.git
      ref: "0.4.1"
  polkawallet_plugin_dbc:
    git:
      url: https://github.com/DeepBrainChain/PolkaWallet_Plugin_DBC.git
      ref: "main"

  # polkawallet_plugin_dbc:
  #   path: ../PolkaWallet_Plugin_DBC

  # polkawallet_plugin_kusama:
  #   path: ../../coding/polkawallet/polkawallet_plugin_kusama
  # polkawallet_plugin_acala:
  #   path: ../../coding/polkawallet/polkawallet_plugin_acala
  # polkawallet_plugin_karura:
  #   path: ../../coding/polkawallet/polkawallet_plugin_karura
  #  polkawallet_plugin_bifrost:
  #    path: ../../coding/polkawallet/polkawallet_plugin_bifrost
  #  polkawallet_plugin_laminar:
  #    path: ../../coding/polkawallet/polkawallet_plugin_laminar
  # polkawallet_plugin_statemine:
  #   path: ../../coding/polkawallet/polkawallet_plugin_statemine
  #  polkawallet_plugin_chainx:
  #    path: ../../coding/polkawallet/polkawallet_plugin_chainx
  #  polkawallet_plugin_edgeware:
  #    path: ../../coding/polkawallet/polkawallet_plugin_edgeware
  #  polkawallet_ui: ^0.3.5
  # polkawallet_ui:
  #    path: ../../coding/polkawallet/ui
  #    git:
  #      url: https://github.com/polkawallet-io/ui.git
  #      ref: 485a9cde97f2446d74a1aeb6d8d63e33683461a5
  #    path: ../../coding/polkawallet/ui
  #  polkawallet_sdk: ^0.3.6
  # polkawallet_sdk:
  #    path: ../../coding/polkawallet/sdk
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter
  flutter_mobx: ^2.0.0
  flutter_svg: ^0.23.0+1
  flutter_swiper: ^1.1.6
  simple_shadow: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  mobx_codegen: ^2.0.1+3
  json_serializable: ^4.1.2
  #  build_runner: ^1.10.9
  #  mobx_codegen: ^1.1.1
  #  json_serializable: ^3.5.1
  flutter_launcher_icons: ^0.9.0
  rive: ^0.7.33

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/public/
    - assets/images/icons/
    - assets/images/plugins/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue.otf
          weight: 700
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf
        - asset: assets/fonts/TitilliumWeb-Black.ttf
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
        - asset: assets/fonts/TitilliumWeb-BoldItalic.ttf
        - asset: assets/fonts/TitilliumWeb-ExtraLight.ttf
        - asset: assets/fonts/TitilliumWeb-ExtraLightItalic.ttf
        - asset: assets/fonts/TitilliumWeb-Italic.ttf
        - asset: assets/fonts/TitilliumWeb-Light.ttf
        - asset: assets/fonts/TitilliumWeb-LightItalic.ttf
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/TitilliumWeb-SemiBoldItalic.ttf
    - family: SF_Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
